version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold-apply
      - terraform plan -destroy -out tfdestroy:
          path: .
          requires:
            - terraform/apply
      - hold-destory:
          type: approval
      - terraform/destroy:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
             - hold-destory
