version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          path: .
      - hold-destory:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          path: .
    working_directory: ~/src
          requires:
             - hold-destory
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
